# Generated by Django 5.2 on 2025-04-15 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher',
            new_name='Instructor',
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name_plural': 'Course Categories'},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='teacher',
            new_name='instructor',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='interest_categories',
            new_name='interests',
        ),
    ]
