# Generated by Django 5.2 on 2025-05-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0003_course_inclusion_course_learn_course_preview_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
