# Generated by Django 5.2 on 2025-05-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0006_alter_course_thumbnail_alter_user_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(default='courses_thumbnail/default_thumbnail.jpg', upload_to='courses_thumbnail/'),
        ),
    ]
