# Generated by Django 5.2 on 2025-05-15 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0008_coursecategory_course_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='qualifications',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'course')},
        ),
        migrations.CreateModel(
            name='InstructorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='instructor_docs/resumes')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='instructor_docs/certificate')),
                ('other_docs', models.FileField(blank=True, null=True, upload_to='instructor_docs/other_docs')),
                ('portfolio', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
