# Generated by Django 5.2 on 2025-05-15 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0009_remove_user_qualifications_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructorapplication',
            options={'verbose_name_plural': 'Instructor Applications'},
        ),
    ]
