# Generated by Django 5.2 on 2025-05-15 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0010_alter_instructorapplication_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_experience', models.CharField(choices=[('none', 'No experience'), ('informal', 'Informal or peer teaching'), ('online', 'Online teaching experience'), ('in_person', 'In-person professional teaching'), ('both', 'Both online and in-person teaching')], max_length=20)),
                ('video_creation_experience', models.CharField(choices=[('none', 'No experience'), ('basic', 'Basic (e.g. Zoom recordings, phone camera)'), ('intermediate', 'Intermediate (basic editing, YouTube uploads)'), ('advanced', 'Advanced (course-quality video production)')], max_length=20)),
                ('agreed_to_policy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='InstructorApplication',
        ),
    ]
