# Generated by Django 5.2 on 2025-06-01 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0013_alter_course_description_alter_course_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(limit_choices_to={'is_published': True}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='lms_app.course'),
        ),
    ]
