# Generated by Django 5.2 on 2025-06-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0015_post_assignment_announcement_quiz_quizquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='submission_type',
            field=models.CharField(choices=[('file', 'File Upload'), ('text', 'Text Area'), ('link', 'URL')], default='file', max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, upload_to='resources/'),
        ),
    ]
