# Generated by Django 5.2 on 2025-07-02 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0016_assignment_submission_type_resource_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='description',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='file',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='link',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='post',
            field=models.OneToOneField(limit_choices_to={'type': 'announcement'}, on_delete=django.db.models.deletion.CASCADE, related_name='announcement', to='lms_app.post'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='post',
            field=models.OneToOneField(limit_choices_to={'type': 'assignment'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='lms_app.post'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='post',
            field=models.OneToOneField(limit_choices_to={'type': 'quiz'}, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='lms_app.post'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='post',
            field=models.OneToOneField(limit_choices_to={'type': 'resource'}, on_delete=django.db.models.deletion.CASCADE, related_name='resource', to='lms_app.post'),
        ),
    ]
